version: "3.9"
services:
  mysql:
    image: mysql:5.7
    container_name: payhere_db
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "db_name"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci