# Generated by Django 3.2.9 on 2021-11-20 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user',
            new_name='email',
        ),
    ]
