# Generated by Django 3.2.9 on 2021-11-20 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0002_rename_user_expense_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='email',
            new_name='user',
        ),
    ]
