# Generated by Django 3.2.9 on 2021-11-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0005_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
