# Generated by Django 3.2.9 on 2021-11-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0006_alter_expense_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
