# Generated by Django 3.2.9 on 2021-11-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0007_remove_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
