# Generated by Django 3.2.9 on 2021-11-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0009_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
