# Generated by Django 3.2.9 on 2021-11-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0012_alter_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='ip',
        ),
    ]
