# Generated by Django 3.2.9 on 2021-11-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0013_remove_expense_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='spent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
